### ISSUE TITLE
Can't fetch trending

### ISSUE THREAD

**Issue by FlurryNight** [JorrinKievit/tmdb-js#1]
Hi, Thank you so much for this package.
I think I'm facing a problem with v3.trending.getTrending() method, I pass the mediaType and timeWindow, but it seems like the timeWindow value is not added to the URL, resulting in a 404.

![image](https://user-images.githubusercontent.com/47457170/233738794-2876758b-c871-4fd7-83e8-04d797f34ad4.png)
![image](https://user-images.githubusercontent.com/47457170/233738915-893418bc-5f4a-419d-a185-5af00d65111e.png)

**Comment by JorrinKievit** [comment]
Thanks for reporting, should be fixed in v1.0.2!

**Comment by JorrinKievit** [comment]
Hm strange, it never published the changes 🤔. Should be fixed in v1.0.3 (hopefully 😂 ). Should set up a pipeline for automatic publishing too.... Thanks for letting me know again!
