### ISSUE TITLE
TV Show episode is missing "runtime" property

### ISSUE THREAD

**Issue by paolodelfino** [JorrinKievit/tmdb-js#13]
[Here](https://developer.themoviedb.org/reference/tv-season-details) we can see that the episode has the runtime but in the api there is no such property

**Comment by JorrinKievit** [comment]
seems like tmdb updated their endpoint, thanks for reporting

**Comment by paolodelfino** [comment]
[This](https://developer.themoviedb.org/reference/tv-season-details) is still outdated. Typescript reference: ```TVSeasonsGetDetailsEpisode```
