### ISSUE TITLE
Npm packages' code tab empty

### ISSUE THREAD

**Issue by paolodelfino** [JorrinKievit/tmdb-js#5]
https://www.npmjs.com/package/tmdb-js-node?activeTab=code it's empty (also web version)

**Comment by JorrinKievit** [comment]
Huh thats odd, something must be going wrong in the automatic deployment in the CI/CD. Will take a look later today

**Comment by JorrinKievit** [comment]
Forgot to build in the pipeline 🤦 , should be fixed in 1.1.1
